### Create un nuevo usuario
POST http://localhost:3000/signup
Content-Type: application/json

{
    "name": "Usuario de Prueba",
    "email": "usuario@prueba.com",
    "password": "usuarioprueba1"
}

###

### Read todos los usuarios
GET http://localhost:3000/users
Accept: application/json

###

### Read un usuario por ID
GET http://localhost:3000/users/id/1
Accept: application/json

###

### Read un usuario por ID
GET http://localhost:3000/users/email/usuario@prueba.com
Accept: application/json

###